# Generated by Django 5.2.1 on 2025-06-02 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(help_text='Digite apenas números, sem espaços ou símbolos (ex: 62999887766)', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Telefone deve conter apenas números (9 ou 11 dígitos)', regex='^\\d{9,11}')], verbose_name='Telefone')),
                ('nome', models.CharField(help_text='Nome completo do participante', max_length=100, verbose_name='Nome Completo')),
                ('senha', models.CharField(help_text='Senha para acesso ao sistema', max_length=128, verbose_name='Senha')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o usuário se cadastrou', verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, help_text='Determina se o usuário pode fazer apostas. Desmarque para desativar.', verbose_name='Usuário Ativo')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'core_usuario',
                'ordering': ['nome'],
            },
        ),
    ]
