# Generated by Django 5.2.1 on 2025-06-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='chave_pix',
            field=models.CharField(default=12345, help_text=' Chave pix para o pagamento dos ganhadores ', max_length=128, verbose_name='chave pix'),
            preserve_default=False,
        ),
    ]
