# Generated by Django 5.2.1 on 2025-06-23 22:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usuario_senha_usuario_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo_escolha', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], help_text="Seu palpite para o sexo do bebê: 'M' para Menino, 'F' para Feminino.", max_length=1)),
                ('valor_aposta', models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='Valor da sua contribuição (mínimo de R$0,01).', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('valor_para_pote', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Valor líquido da contribuição após a dedução da taxa.', max_digits=8, null=True)),
                ('data_aposta', models.DateTimeField(auto_now_add=True)),
                ('aposta_valida', models.BooleanField(default=False, help_text='Indica se a aposta foi validada pelo administrador.')),
                ('comprovante_pagamento', models.FileField(blank=True, help_text='Anexe o comprovante de pagamento (imagem ou PDF).', null=True, upload_to='comprovantes/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aposta',
                'verbose_name_plural': 'Apostas',
                'ordering': ['-data_aposta'],
            },
        ),
    ]
