# Generated by Django 5.2.1 on 2025-06-27 16:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='aposta_valida',
            field=models.BooleanField(default=False, help_text='Indica se a aposta foi validada pelo administrador.', verbose_name='Aposta Válida'),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='comprovante_pagamento',
            field=models.FileField(blank=True, help_text='Anexe o comprovante de pagamento (imagem ou PDF).', null=True, upload_to='comprovantes/', verbose_name='Comprovante de Pagamento'),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='data_aposta',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Aposta'),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='sexo_escolha',
            field=models.CharField(choices=[('M', 'Menino'), ('F', 'Menina')], help_text="Seu palpite para o sexo do bebê: 'M' para Menino, 'F' para Menina.", max_length=1, verbose_name='Palpite'),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='valor_aposta',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='Valor da sua contribuição (mínimo de R$0,01).', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor da Aposta'),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='valor_para_pote',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Valor líquido da contribuição após a dedução da taxa.', max_digits=8, null=True, verbose_name='Valor para o Pote'),
        ),
    ]
