# Generated by Django 5.2.1 on 2025-07-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_aposta_aposta_valida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aposta',
            name='aposta_valida',
        ),
        migrations.AddField(
            model_name='aposta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Pagamento'), ('aguardando_validação', 'Aguardado Validação'), ('valida', 'Válida'), ('cancelada', 'Cancelada'), ('rejeitada', 'Rejeitada')], default='pendente', help_text='Status atual da aposta (ex: pendente, aguardando validação, válida).', max_length=20, verbose_name='Status da Aposta'),
        ),
    ]
