# Generated by Django 5.2.1 on 2025-07-11 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_aposta_aposta_valida_aposta_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aposta',
            name='comprovante_pagamento',
        ),
    ]
