# Generated by Django 5.2.1 on 2025-08-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='chave_pix',
            field=models.CharField(default='', help_text='Chave PIX para o pagamento dos ganhadores', max_length=128, verbose_name='Chave PIX'),
            preserve_default=False,
        ),
    ]
