# Generated by Django 5.2.1 on 2025-08-12 23:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_usuario_chave_pix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aposta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente de Pagamento'), ('aguardando_validacao', 'Aguardando Validação'), ('valida', 'Válida'), ('cancelada', 'Cancelada'), ('rejeitada', 'Rejeitada')], default='pendente', help_text='Status atual da aposta (ex: pendente, aguardando validação, válida).', max_length=20, verbose_name='Status da Aposta'),
        ),
        migrations.AlterField(
            model_name='aposta',
            name='valor_para_pote',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Valor líquido da contribuição após a dedução da taxa.', max_digits=8, verbose_name='Valor para o Pote'),
        ),
        migrations.AddIndex(
            model_name='aposta',
            index=models.Index(fields=['status'], name='core_aposta_status_784adb_idx'),
        ),
        migrations.AddIndex(
            model_name='aposta',
            index=models.Index(fields=['sexo_escolha', 'status'], name='core_aposta_sexo_es_c0e813_idx'),
        ),
        migrations.AddIndex(
            model_name='aposta',
            index=models.Index(fields=['-data_aposta'], name='core_aposta_data_ap_a1216e_idx'),
        ),
    ]
