# Generated by Django 5.2.1 on 2025-08-13 15:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_aposta_status_alter_aposta_valor_para_pote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aposta',
            name='encerrado',
            field=models.BooleanField(default=False, help_text='Indica se a aposta foi encerrada e não aceita mais novos palpites', verbose_name='Aposta encerrada'),
        ),
        migrations.AddField(
            model_name='aposta',
            name='valor_para_pagar',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Valor preenchido no momento em que as apostas encerrarem.', max_digits=8, null=True, verbose_name='Valor do pagamento dos ganhadores'),
        ),
    ]
