# Generated by Django 5.2.1 on 2025-08-22 17:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aposta_encerrado_aposta_valor_para_pagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Determina se o usuário pode fazer palpites. Desmarque para desativar.', verbose_name='Usuário Ativo'),
        ),
        migrations.CreateModel(
            name='palpite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo_escolha', models.CharField(choices=[('M', 'Menino'), ('F', 'Menina')], help_text="Seu palpite para o sexo do bebê: 'M' para Menino, 'F' para Menina.", max_length=1, verbose_name='Palpite')),
                ('valor_palpite', models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='Valor da sua contribuição (mínimo de R$0,01).', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor da palpite')),
                ('valor_para_pote', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Valor líquido da contribuição após a dedução da taxa.', max_digits=8, verbose_name='Valor para o Pote')),
                ('data_palpite', models.DateTimeField(auto_now_add=True, verbose_name='Data da palpite')),
                ('valor_para_pagar', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Valor preenchido no momento em que as palpites encerrarem.', max_digits=8, null=True, verbose_name='Valor do pagamento dos ganhadores')),
                ('encerrado', models.BooleanField(default=False, help_text='Indica se a palpite foi encerrada e não aceita mais novos palpites', verbose_name='palpite encerrada')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Pagamento'), ('aguardando_validacao', 'Aguardando Validação'), ('valida', 'Válida'), ('cancelada', 'Cancelada'), ('rejeitada', 'Rejeitada')], default='pendente', help_text='Status atual da palpite (ex: pendente, aguardando validação, válida).', max_length=20, verbose_name='Status da palpite')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'palpite',
                'verbose_name_plural': 'palpites',
                'ordering': ['-data_palpite'],
            },
        ),
        migrations.DeleteModel(
            name='Aposta',
        ),
        migrations.AddIndex(
            model_name='palpite',
            index=models.Index(fields=['status'], name='core_palpit_status_436c13_idx'),
        ),
        migrations.AddIndex(
            model_name='palpite',
            index=models.Index(fields=['sexo_escolha', 'status'], name='core_palpit_sexo_es_55b4f7_idx'),
        ),
        migrations.AddIndex(
            model_name='palpite',
            index=models.Index(fields=['-data_palpite'], name='core_palpit_data_pa_4c3f2a_idx'),
        ),
    ]
