# Generated by Django 5.2.1 on 2025-08-23 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_usuario_ativo_palpite_delete_aposta_and_more'),
    ]

    operations = [
    ]
